### ISSUE TITLE
Duplicate message

### ISSUE THREAD

**Issue by zsnmwy** [open-dingtalk/dingtalk-tutorial-nodejs#1]
Now in the official demo, it will receive the duplicate message.

The dingtalk-stream should be upgraded to `v2.1.4` and called the method `socketCallBackResponse`.

https://github.com/open-dingtalk/dingtalk-stream-sdk-nodejs/commit/a96e84fef68e10c954f4c28e5e066ec8200c1a74#

**Comment by chzealot** [comment]
推送失败重试引起，已经优化
